version: '3'

vars:
  VERSION:
    sh: cat version
  GITHUB_URL: https://github.com/alexklibisz/elastiknn

includes:
  jvm: Taskfile.jvm.yml
  py: 
    taskfile: client-python/Taskfile.yml
    dir: client-python
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs
  
tasks:

  clean:
    deps: 
      - jvm:clean
      - py:clean

  check-installs:
    cmds:
      - "task --version"
      - "javac -version"
      - "python3 --version"
      - "docker-compose --version"
      - "ruby --version"
      - "gem --version"
