version: '3'

vars:
  VERSION:
    sh: cat version
  PROJECT_ROOT:
    sh: pwd
  GITHUB_URL: https://github.com/alexklibisz/elastiknn
  MAVEN_URL: https://repo1.maven.org/maven2/com/klibisz/elastiknn
  CMD_GRADLE: "./gradlew --console=plain"
  SITE_SSH_ALIAS: elastiknn-site
  SITE_MAIN_DIR: elastiknn.com
  SITE_ARCH_DIR: archive.elastiknn.com

includes:
  jvm:
    taskfile: taskfiles/Taskfile.jvm.yaml
    dir: .
  cluster:
    taskfile: taskfiles/Taskfile.cluster.yaml
    dir: .
  py:
    taskfile: taskfiles/Taskfile.python.yaml
    dir: client-python
  docs:
    taskfile: taskfiles/Taskfile.docs.yaml
    dir: docs
  benchmarks:
    taskfile: taskfiles/Taskfile.benchmarks.yaml
    dir: elastiknn-benchmarks
  
tasks:
  clean:
    desc: Call clean commands in included taskfiles
    deps: 
      - jvm:clean
      - py:clean
