version: '3'

vars: 
  CMD_GRADLE: "./gradlew --console=plain"  

tasks:

  clean:
    deps: [jvm-clean]

  jvm-clean: "{{ .CMD_GRADLE }} clean"

  jvm-compile:
    sources: ["**/*.java", "**/*.scala"]
    cmds:
      - "{{ .CMD_GRADLE }} compileScala compileJava compileTestScala compileTestJava"

  jvm-test: "{{ .CMD_GRADLE }} test"

  es-run-gradle:
    cmds:
      - "{{ .CMD_GRADLE }} :plugin:run --data-dir={{ .DATA_DIR }} -Dtests.heap.size={{ .HEAP }} -Dtests.es.node.processors={{ .THREADS }} -Dtests.es.thread_pool.search.size={{ .THREADS }} {{ .DEBUG }}"
    vars:
      DATA_DIR: "/tmp/elastiknn"
      THREADS: 1
      HEAP: 4G

  es-run-debug:
    cmds:
      - task: es-run-gradle
        vars: {DEBUG: "--debug-jvm"}


