version: '3'

tasks:
  venv:
    desc: Create python virtual environment
    cmds:
      - python3 --version
      - python3 -m pip install --quiet virtualenv
      - python3 -m virtualenv -p python3.7 venv
      - touch requirements.txt
    generates:
      - venv
    status:
      - test -d venv

  clean:
    desc: Delete python virtual environment
    cmds: 
      - rm -rf venv

  requirements:
    desc: Install python dependencies from requirements.txt
    deps:
      - venv
    sources:
      - venv/bin/*
      - setup.py
      - requirements*txt
    cmds:
      - venv/bin/pip install -r requirements.txt
      - venv/bin/pip install -r requirements-build.txt

  test:
    desc: Run python tests against local cluster
    deps:
      - requirements
    sources:
      - elastiknn/**/*.py
      - setup.py
    cmds:
      - venv/bin/python -m pytest -v -s -o log_cli=True

  docs:
    desc: Generate python docs
    deps:
      - requirements
    sources:
      - elastiknn/**/*.py
      - setup.py
    cmds:
      - rm -rf pdoc
      - venv/bin/pdoc3 --html elastiknn -c show_type_annotations=True -o pdoc
    
  publish-local:
    desc: Publish python library locally
    deps:
      - requirements
    cmds:
      - rm -rf dist
      - venv/bin/python setup.py --version {{ .VERSION }} sdist bdist_wheel
      - ls dist

  publish-snapshot:
    desc: Publish python library to testpypi
    cmds:
      - task: publish-local
        force: True
      - venv/bin/python -m twine upload -r testpypi --verbose dist/*

  publish-docs:
    desc: Publish python docs to elastiknn.com server
    status:
      - curl -f -s -o /dev/null https://{{ .SITE_ARCH_DIR }}/{{ .VERSION }}/pdoc/index.html
    cmds:
      - task: docs
        force: True
      - ssh {{ .SITE_SSH_ALIAS }} mkdir -p {{ .SITE_ARCH_DIR }}/{{ .VERSION }}
      - rsync -av --delete pdoc/elastiknn/ {{ .SITE_SSH_ALIAS }}:{{ .SITE_ARCH_DIR }}/{{ .VERSION }}/pdoc
      - rsync -av --delete pdoc/elastiknn/ {{ .SITE_SSH_ALIAS }}:{{ .SITE_MAIN_DIR }}/docs/pdoc
    

  publish-release:
    desc: Publish python library to pypi
    status:
      - curl -f -s -o /dev/null https://pypi.org/project/elastiknn-client/{{ .VERSION }}/
    cmds:
      - task: publish-local
        force: True
      - task: docs
        force: True
      - venv/bin/python -m twine upload -r pypi --verbose dist/*
      
