# Useful for development and debugging inside the k8s cluster.
apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  nodeSelector:
    beta.kubernetes.io/instance-type: c5.xlarge
  containers:
    - name: dev
      image: ubuntu:20.04
      resources:
        limits:
          cpu: 3
          memory: 6Gi
      command: ["tail"]
      args: ["-f", "/dev/null"]
      env:
        - name: AWS_ACCESS_KEY_ID
          value: ${AWS_ACCESS_KEY_ID}
        - name: AWS_SECRET_ACCESS_KEY
          value: ${AWS_SECRET_ACCESS_KEY}
    - name: dind
      image: docker:19.03-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-pvc
          mountPath: /var/lib/docker
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi

