apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.3
  image: 788008650827.dkr.ecr.us-east-1.amazonaws.com/elastiknn-benchmarks-cluster.elastiknn
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 3
    config:
      thread_pool.search.size: 8
      xpack.security.authc:
        anonymous:
          username: anonymous
          roles: superuser
          authz_exception: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: storage-10-iops
    podTemplate:
      spec:
        nodeSelector:
          beta.kubernetes.io/instance-type: c5.4xlarge
        initContainers:
          - name: set-max-map-count
            image: ubuntu:19.04
            imagePullPolicy: IfNotPresent
            command: ["sysctl", "-w", "vm.max_map_count=262144"]
            securityContext:
              privileged: true
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: >-
                  -XX:MinRAMPercentage=60
                  -XX:MaxRAMPercentage=60
                  -XX:+UseG1GC
                  -XX:G1ReservePercent=25
                  -XX:InitiatingHeapOccupancyPercent=30
            resources:
              requests:
                cpu: 8
                memory: 8Gi
              limits:
                cpu: 8
                memory: 8Gi


