version: "3"

services:
  # Single master node.
  elasticsearch_master:
    build:
      context: ${ES_CONTEXT:-../es74x}
      dockerfile: Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - node.master=true
      - node.data=false
      - node.ml=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  # Single client node exposing port 9200.
  elasticsearch_client:
    build:
      context: ${ES_CONTEXT:-../es74x}
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    environment:
      - node.name=elasticsearch_client
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - discovery.zen.ping.unicast.hosts=elasticsearch_master
      - node.master=false
      - node.data=false
      - node.ml=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  # 1 or more data nodes (--scale elasticsearch_data=n)
  elasticsearch_data:
    build:
      context: ${ES_CONTEXT:-../es74x}
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - discovery.zen.ping.unicast.hosts=elasticsearch_master
      - node.master=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

