# docker compose setup for running tests and micro-benchmarks.
# Github's virtual environments have 2 CPUs, 7GB memory, 14GB SSD.
# Important to run > 1 node because some parts of the plugin
# deal with communication/serialization between nodes.
version: "2"

services:
  # Single master node.
  elasticsearch_master:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - node.roles=master
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 700m
    mem_reservation: 700m
    cpus: 0.5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  elasticsearch_data:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - node.name=elasticsearch_data
      - node.roles=data
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - discovery.seed_hosts=elasticsearch_master
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - elastiknn.jdk-incubator-vector.enabled=true
      - ES_JAVA_OPTS=--add-modules jdk.incubator.vector
    ports:
      - "8097:8097"
    mem_limit: 1300m
    mem_reservation: 1300m
    cpus: 1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
