version: "2"

services:
  elasticsearch_master:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 8000m
    mem_reservation: 8000m
    cpus: 0.5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
