version: "2"

services:
  elasticsearch_master:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
      - discovery.type=single-node
      - elastiknn.jdk-incubator-vector.enabled=true
      - ES_JAVA_OPTS=--add-modules jdk.incubator.vector -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=6000 -Dcom.sun.management.jmxremote.rmi.port=6000 -Djava.rmi.server.hostname=localhost
    ports:
      - "9200:9200"
      - "6000:6000"
    mem_limit: 12000m
    mem_reservation: 12000m
    cpus: 2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
