FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
# RUN elasticsearch-plugin install -b https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE48/elastiknn-0.1.0-PRE48_es7.9.2.zip
RUN elasticsearch-plugin install -b https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE48-PR196-SNAPSHOT/elastiknn-0.1.0-PRE48-PR196-SNAPSHOT_es7.9.2.zip