version: "3.8"

services:
  elasticsearch_master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch_master
      - node.master=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms4G -Xmx4G
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
volumes:
  data01:
    driver: local