FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
RUN elasticsearch-plugin install -b https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE47/elastiknn-0.1.0-PRE47_es7.9.2.zip
