version: "3"

services:

  # App container. Run sbt docker:stage to generate the dockerfile.
  app:
    build:
      context: webapp/target/docker/stage
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 9000:9000
      - 8097:8097
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - PLAY_HTTP_SECRET_KEY=${PLAY_HTTP_SECRET_KEY:-changeme}
      - JAVA_OPTS=-Xms50M -Xmx1G
    restart: on-failure:3

  # Single elasticsearch container.
  elasticsearch:
    build:
      context: ${ES_CONTEXT:-../../plugin}
      dockerfile: Dockerfile
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=demo
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms5G -Xmx5G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    restart: on-failure:3
