# Use envsubst to "render" the file.
# Seems like the most I can allocate on a c5.4xlarge is 15 CPUs and 26Gi memory.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: elastiknn-benchmark-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/elastiknn-benchmarks-cluster.driver
        imagePullPolicy: "Always"
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
      nodeSelector:
        beta.kubernetes.io/instance-type: c5.4xlarge
      sidecars:
        - name: elastiknn
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/elastiknn-benchmarks-cluster.elastiknn
          imagePullPolicy: "Always"
          env:
            - name: discovery.type
              value: single-node
          resources:
            requests:
              cpu: 14
              memory: 22Gi
            limits:
              cpu: 14
              memory: 22Gi
