package com.klibisz.elastiknn.storage;


// Code generated by colf(1); DO NOT EDIT.


import static java.lang.String.format;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.InputMismatchException;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;


/**
 * Data bean with built-in serialization support.

 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@javax.annotation.Generated(value="colf(1)", comments="Colfer from schema file storage.colf")
public class ColferSparseBool implements Serializable {

	/** The upper limit for serial byte sizes. */
	public static int colferSizeMax = 16 * 1024 * 1024;

	/** The upper limit for the number of elements in a list. */
	public static int colferListMax = 64 * 1024;




	public int totalIndices;

	public ColferUInt32[] trueIndices;


	/** Default constructor */
	public ColferSparseBool() {
		init();
	}

	private static final ColferUInt32[] _zeroTrueIndices = new ColferUInt32[0];

	/** Colfer zero values. */
	private void init() {
		trueIndices = _zeroTrueIndices;
	}

	/**
	 * {@link #reset(InputStream) Reusable} deserialization of Colfer streams.
	 */
	public static class Unmarshaller {

		/** The data source. */
		protected InputStream in;

		/** The read buffer. */
		public byte[] buf;

		/** The {@link #buf buffer}'s data start index, inclusive. */
		protected int offset;

		/** The {@link #buf buffer}'s data end index, exclusive. */
		protected int i;


		/**
		 * @param in the data source or {@code null}.
		 * @param buf the initial buffer or {@code null}.
		 */
		public Unmarshaller(InputStream in, byte[] buf) {
			// TODO: better size estimation
			if (buf == null || buf.length == 0)
				buf = new byte[Math.min(ColferSparseBool.colferSizeMax, 2048)];
			this.buf = buf;
			reset(in);
		}

		/**
		 * Reuses the marshaller.
		 * @param in the data source or {@code null}.
		 * @throws IllegalStateException on pending data.
		 */
		public void reset(InputStream in) {
			if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
			this.in = in;
			this.offset = 0;
			this.i = 0;
		}

		/**
		 * Deserializes the following object.
		 * @return the result or {@code null} when EOF.
		 * @throws IOException from the input stream.
		 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
		 * @throws InputMismatchException when the data does not match this object's schema.
		 */
		public ColferSparseBool next() throws IOException {
			if (in == null) return null;

			while (true) {
				if (this.i > this.offset) {
					try {
						ColferSparseBool o = new ColferSparseBool();
						this.offset = o.unmarshal(this.buf, this.offset, this.i);
						return o;
					} catch (BufferUnderflowException e) {
					}
				}
				// not enough data

				if (this.i <= this.offset) {
					this.offset = 0;
					this.i = 0;
				} else if (i == buf.length) {
					byte[] src = this.buf;
					// TODO: better size estimation
					if (offset == 0) this.buf = new byte[Math.min(ColferSparseBool.colferSizeMax, this.buf.length * 4)];
					System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
					this.i -= this.offset;
					this.offset = 0;
				}
				assert this.i < this.buf.length;

				int n = in.read(buf, i, buf.length - i);
				if (n < 0) {
					if (this.i > this.offset)
						throw new InputMismatchException("colfer: pending data with EOF");
					return null;
				}
				assert n > 0;
				i += n;
			}
		}

	}


	/**
	 * Serializes the object.
	 * All {@code null} elements in {@link #trueIndices} will be replaced with a {@code new} value.
	 * @param out the data destination.
	 * @param buf the initial buffer or {@code null}.
	 * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
	 *  Otherwise the return is a new buffer, large enough to hold the whole serial.
	 * @throws IOException from {@code out}.
	 * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 */
	public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
		// TODO: better size estimation
		if (buf == null || buf.length == 0)
			buf = new byte[Math.min(ColferSparseBool.colferSizeMax, 2048)];

		while (true) {
			int i;
			try {
				i = marshal(buf, 0);
			} catch (BufferOverflowException e) {
				buf = new byte[Math.min(ColferSparseBool.colferSizeMax, buf.length * 4)];
				continue;
			}

			out.write(buf, 0, i);
			return buf;
		}
	}

	/**
	 * Serializes the object.
	 * All {@code null} elements in {@link #trueIndices} will be replaced with a {@code new} value.
	 * @param buf the data destination.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferOverflowException when {@code buf} is too small.
	 * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 */
	public int marshal(byte[] buf, int offset) {
		int i = offset;

		try {
			if (this.totalIndices != 0) {
				int x = this.totalIndices;
				if ((x & ~((1 << 21) - 1)) != 0) {
					buf[i++] = (byte) (0 | 0x80);
					buf[i++] = (byte) (x >>> 24);
					buf[i++] = (byte) (x >>> 16);
					buf[i++] = (byte) (x >>> 8);
				} else {
					buf[i++] = (byte) 0;
					while (x > 0x7f) {
						buf[i++] = (byte) (x | 0x80);
						x >>>= 7;
					}
				}
				buf[i++] = (byte) x;
			}

			if (this.trueIndices.length != 0) {
				buf[i++] = (byte) 1;
				ColferUInt32[] a = this.trueIndices;

				int x = a.length;
				if (x > ColferSparseBool.colferListMax)
					throw new IllegalStateException(format("colfer: com/klibisz/elastiknn/storage.ColferSparseBool.trueIndices length %d exceeds %d elements", x, ColferSparseBool.colferListMax));
				while (x > 0x7f) {
					buf[i++] = (byte) (x | 0x80);
					x >>>= 7;
				}
				buf[i++] = (byte) x;

				for (int ai = 0; ai < a.length; ai++) {
					ColferUInt32 o = a[ai];
					if (o == null) {
						o = new ColferUInt32();
						a[ai] = o;
					}
					i = o.marshal(buf, i);
				}
			}

			buf[i++] = (byte) 0x7f;
			return i;
		} catch (ArrayIndexOutOfBoundsException e) {
			if (i - offset > ColferSparseBool.colferSizeMax)
				throw new IllegalStateException(format("colfer: com/klibisz/elastiknn/storage.ColferSparseBool exceeds %d bytes", ColferSparseBool.colferSizeMax));
			if (i > buf.length) throw new BufferOverflowException();
			throw e;
		}
	}

	/**
	 * Deserializes the object.
	 * @param buf the data source.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
	 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 * @throws InputMismatchException when the data does not match this object's schema.
	 */
	public int unmarshal(byte[] buf, int offset) {
		return unmarshal(buf, offset, buf.length);
	}

	/**
	 * Deserializes the object.
	 * @param buf the data source.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @param end the index limit for {@code buf}, exclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
	 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 * @throws InputMismatchException when the data does not match this object's schema.
	 */
	public int unmarshal(byte[] buf, int offset, int end) {
		if (end > buf.length) end = buf.length;
		int i = offset;

		try {
			byte header = buf[i++];

			if (header == (byte) 0) {
				int x = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					x |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				this.totalIndices = x;
				header = buf[i++];
			} else if (header == (byte) (0 | 0x80)) {
				this.totalIndices = (buf[i++] & 0xff) << 24 | (buf[i++] & 0xff) << 16 | (buf[i++] & 0xff) << 8 | (buf[i++] & 0xff);
				header = buf[i++];
			}

			if (header == (byte) 1) {
				int length = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					length |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (length < 0 || length > ColferSparseBool.colferListMax)
					throw new SecurityException(format("colfer: com/klibisz/elastiknn/storage.ColferSparseBool.trueIndices length %d exceeds %d elements", length, ColferSparseBool.colferListMax));

				ColferUInt32[] a = new ColferUInt32[length];
				for (int ai = 0; ai < length; ai++) {
					ColferUInt32 o = new ColferUInt32();
					i = o.unmarshal(buf, i, end);
					a[ai] = o;
				}
				this.trueIndices = a;
				header = buf[i++];
			}

			if (header != (byte) 0x7f)
				throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
		} finally {
			if (i > end && end - offset < ColferSparseBool.colferSizeMax) throw new BufferUnderflowException();
			if (i < 0 || i - offset > ColferSparseBool.colferSizeMax)
				throw new SecurityException(format("colfer: com/klibisz/elastiknn/storage.ColferSparseBool exceeds %d bytes", ColferSparseBool.colferSizeMax));
			if (i > end) throw new BufferUnderflowException();
		}

		return i;
	}

	// {@link Serializable} version number.
	private static final long serialVersionUID = 2L;

	// {@link Serializable} Colfer extension.
	private void writeObject(ObjectOutputStream out) throws IOException {
		// TODO: better size estimation
		byte[] buf = new byte[1024];
		int n;
		while (true) try {
			n = marshal(buf, 0);
			break;
		} catch (BufferUnderflowException e) {
			buf = new byte[4 * buf.length];
		}

		out.writeInt(n);
		out.write(buf, 0, n);
	}

	// {@link Serializable} Colfer extension.
	private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
		init();

		int n = in.readInt();
		byte[] buf = new byte[n];
		in.readFully(buf);
		unmarshal(buf, 0);
	}

	// {@link Serializable} Colfer extension.
	private void readObjectNoData() throws ObjectStreamException {
		init();
	}

	/**
	 * Gets com/klibisz/elastiknn/storage.ColferSparseBool.totalIndices.
	 * @return the value.
	 */
	public int getTotalIndices() {
		return this.totalIndices;
	}

	/**
	 * Sets com/klibisz/elastiknn/storage.ColferSparseBool.totalIndices.
	 * @param value the replacement.
	 */
	public void setTotalIndices(int value) {
		this.totalIndices = value;
	}

	/**
	 * Sets com/klibisz/elastiknn/storage.ColferSparseBool.totalIndices.
	 * @param value the replacement.
	 * @return {link this}.
	 */
	public ColferSparseBool withTotalIndices(int value) {
		this.totalIndices = value;
		return this;
	}

	/**
	 * Gets com/klibisz/elastiknn/storage.ColferSparseBool.trueIndices.
	 * @return the value.
	 */
	public ColferUInt32[] getTrueIndices() {
		return this.trueIndices;
	}

	/**
	 * Sets com/klibisz/elastiknn/storage.ColferSparseBool.trueIndices.
	 * @param value the replacement.
	 */
	public void setTrueIndices(ColferUInt32[] value) {
		this.trueIndices = value;
	}

	/**
	 * Sets com/klibisz/elastiknn/storage.ColferSparseBool.trueIndices.
	 * @param value the replacement.
	 * @return {link this}.
	 */
	public ColferSparseBool withTrueIndices(ColferUInt32[] value) {
		this.trueIndices = value;
		return this;
	}

	@Override
	public final int hashCode() {
		int h = 1;
		h = 31 * h + this.totalIndices;
		for (ColferUInt32 o : this.trueIndices) h = 31 * h + (o == null ? 0 : o.hashCode());
		return h;
	}

	@Override
	public final boolean equals(Object o) {
		return o instanceof ColferSparseBool && equals((ColferSparseBool) o);
	}

	public final boolean equals(ColferSparseBool o) {
		if (o == null) return false;
		if (o == this) return true;
		return o.getClass() == ColferSparseBool.class
			&& this.totalIndices == o.totalIndices
			&& java.util.Arrays.equals(this.trueIndices, o.trueIndices);
	}

}
