version: '3'

tasks:

  install-bundler:
    status:
      - bundle --version
    cmds:
      - gem install bundler

  dev: 
    deps:
      - install-bundler
    cmds:
      - bundle exec jekyll serve

  compile:
    sources:
      - "**/*.md"
      - "**/*.html"
    deps:
      - install-bundler
    cmds:
      - bundle exec jekyll build
