version: '3'

tasks:

  install-bundler:
    status:
      - bundle --version
    cmds:
      - gem install bundler

  dev: 
    desc: Start local development server.
    deps:
      - install-bundler
    cmds:
      - bundle install
      - bundle exec jekyll serve

  compile:
    desc: Compile docs into a static site.
    sources:
      - "**/*.md"
      - "**/*.html"
    deps:
      - install-bundler
    cmds:
      - bundle install
      - bundle exec jekyll build

  publish:
    desc: Publish docs to elastiknn.com server.
    status:
      - curl -f -o /dev/null https://{{ .SITE_MAIN_DIR }}/{{ .VERSION }}.html
    cmds:
      - task: compile
        force: True
      - echo {{ .VERSION }} > _site/{{ .VERSION }}.html
      - rsync -av --delete --exclude docs _site/ {{ .SITE_SSH_ALIAS }}:{{ .SITE_MAIN_DIR }}
