name: "CI 2"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  show-github-context:
    runs-on: ubuntu-20.04
    steps:
      - name: Show Github Context
        run: echo "${{ toJson(github) }}"
  
  test-jvm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Install Task
        run: sudo snap install task --classic
      - name: Compile
        run: task jvm:compile
      - name: Publish Local
        run: task jvm:publish-local
      - name: Docs
        run: task jvm:docs
      - name: Run Cluster
        run: task cluster:run
      - name: Test
        run: task jvm:test
      - name: Cluster Logs
        if: failure()
        run: task cluster:logs
      
  # Ideally the snapshot release would run only if the tests pass, but right now
  # there's no way to make a job conditional on another job.
  snapshot-pr:
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: |
          sudo snap install --classic task hub
          python3 -m pip install setuptools
      - name: Publish to PyPi
        run: task py:publish-snapshot

  snapshot-master:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
        
  test-python:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Install Task
        run: sudo snap install task --classic
      - name: Publish Local
        run: task jvm:publish-local
      - name: Docs
        run: task jvm:docs
      - name: Run Cluster
        run: task cluster:run
      - name: Test
        run: task py:test
      - name: Cluster Logs
        run: task cluster:logs

  build-examples:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Task
        run: sudo snap install task --classic
      - name: Install Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 14
      - name: Build SBT client example
        run: |
          task jvm:publish-local
          cd examples/scala-sbt-client-usage && sbt -batch run

  build-jekyll-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Task
        run: sudo snap install task --classic
      - name: Compile Jekyll Site
        run: "task docs:compile"
