name: "CI 2"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  show-github-context:
    runs-on: ubuntu-20.04
    steps:
      - name: Show Github Context
        run: echo "${{ toJson(github) }}"
  
  test-jvm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Task
        run: sudo snap install task --classic
      - name: Compile
        run: task jvm:compile
      - name: Run Cluster
        run: task cluster:run
      - name: Test
        run: task jvm:test
      - name: Cluster Logs
        run: task cluster:logs
  
  test-python:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install Task
        run: sudo snap install task --classic
      - name: Run Cluster
        run: task cluster:run
      - name: Test
        run: task py:test
      - name: Cluster Logs
        run: task cluster:logs

  build-jekyll-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Task
        run: sudo snap install task --classic
      - name: Compile Jekyll Site
        run: "task docs:compile"
