name: Publish Docs

on:
  pull_request:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        
      - name: copy gemfile
        run: cp docs/Gemfile .      

      # Specify the Jekyll source location as a parameter
      - uses: helaili/jekyll-action@2.0.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          JEKYLL_SRC: 'docs'
