# Releases snapshots of the plugin and client libraries for every push to master
# and for specific slash-commands on PRs.
name: Release Snapshots
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  release-snapshots:
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{ toJson(github) }}
