# Release snapshots for every push to master and for specific slash-commands on PR comments.
name: Release Snapshots
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check for /release-snapshots commands
        run: |
          echo "::set-env name=MATCHING::$(echo ${{ toJson(github) }} | python3 .github/scripts/check-slash-cmd.py /release-snapshots)"
      - name: Run Release
        if: env.MATCHING > 0
        run: echo "Releasing snapshots..."

#  inspect:
#    runs-on: ubuntu-16.04
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: Dump job context
#        env:
#          JOB_CONTEXT: ${{ toJson(job) }}
#        run: echo "$JOB_CONTEXT"
#      - name: Dump steps context
#        env:
#          STEPS_CONTEXT: ${{ toJson(steps) }}
#        run: echo "$STEPS_CONTEXT"
#      - name: Dump runner context
#        env:
#          RUNNER_CONTEXT: ${{ toJson(runner) }}
#        run: echo "$RUNNER_CONTEXT"
#      - name: Dump strategy context
#        env:
#          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#        run: echo "$STRATEGY_CONTEXT"
#      - name: Dump matrix context
#        env:
#          MATRIX_CONTEXT: ${{ toJson(matrix) }}
#        run: echo "$MATRIX_CONTEXT"
