# Placeholder for running a release when a PR is merged into the release branch.
# This seems to be the only way you can manually invoke a release.
name: Release
on:
  push:
    branches: 
      - release
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, release!
