name: Release Docs
on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release-docs:
    needs: release-python-client
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on:
      - ubuntu-22.04
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'pip'
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Jekyll Site
        run: |
          sudo chown -R runneradmin:runneradmin docs
          task docsCompile
          sudo chown -R runner:docker docs
      - name: Generate Python Docs
        run: |
          task pyDocs
          mkdir -p docs/_site/docs
          mv client-python/pdoc/elastiknn docs/_site/docs/pdoc
      - name: Configure Pages
        uses: actions/configure-pages@v2
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
