# Placeholder for running a release when a PR is merged and the version file has changed.
name: Release
on:
  push:
    branches: 
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Check if version file changed
      run: echo "::set-env name=CHANGED::$(git diff --name-only HEAD~1 HEAD | grep version | wc -l)"
    - name: Release if version changed
      if: env.CHANGED == 1
      run: echo "Run the release"
