name: Release Snapshots
on:
  push:
    branches: 
      - master
      - release-snapshots
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.2
    - name: Import GPG Key
#       env: # Or as an environment variable
#         TEST: ${{ secrets.TEST }}
      run: echo ${{ secrets.TEST }}
