float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: Exact
    disabled: true
    docker_tag: ann-benchmarks-elastiknn
    module: ann_benchmarks.algorithms.elastiknn
    name: elastiknn-exact
    run_groups:
      exact:
        args: []
  euclidean:
  - base_args: []
    constructor: L2Lsh
    disabled: true
    docker_tag: ann-benchmarks-elastiknn
    module: ann_benchmarks.algorithms.elastiknn
    name: elastiknn-l2lsh
    run_groups:
      elastiknn-l2lsh:
        args: [[125,150,175,200], [7,8,9], [3900,4000,4100]]
        query_args: [[500,750,1000,1250], [0,1,2]]
